name: Deploy dev

on:
  pull_request:
    branchs:
      - dev
      - qa
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Set environment variables
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Build with Maven
        run: |
          mvn clean package -Ddb.username=${DB_USERNAME} -Ddb.url=${DB_URL} -Ddb.password=${DB_PASSWORD}

      - name: Run tests
        run: |
          mvn test -Ddb.username=${DB_USERNAME} -Ddb.url=${DB_URL} -Ddb.password=${DB_PASSWORD}